global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'agent'
    static_configs:
      - targets: ['agent:8081']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:4317']
